### ISSUE TITLE
Fidelity Investment Shenanigans

### ISSUE THREAD

**Issue by aclindsa** [csingley/ofxtools#109]
Fidelity appears to now be requiring that ':443' be added to URLs:

> https://ofx.fidelity.com:443/ftgw/OFX/clients/download

succeeds, while

> https://ofx.fidelity.com/ftgw/OFX/clients/download

results in HTTP 403 starting December 3rd. However, the profile response from hitting the :443 URL returns the URL *not* containing ':443'. Because ofxtools uses the profile response for the subsequent statement request, the statement request then returns 403 even though the profile request succeeded. Sigh.

**Comment by csingley** [comment]
Good lord.  I should be numb by now, but lying through an API is still fairly appalling.

Perhaps we'd better revisit the idea of adding a boolean arg to the various `request_*()` methods of `OFXClient`, as per the PR I talked you out of.

**Comment by aclindsa** [comment]
I was just about to post an update (I think you're going to enjoy this). This has now been resolved by Fidelity. They reverted the behavior as of a couple hours ago.

But I contacted Fidelity before that happened and here's the meaty part of the exchange:

> Fidelity: "Currently, we are preventing access to certain Open Financial Exchanges (OFX). However, we will re-enable this feature at end of business today."
> Fidelity: "This is a proactive step to maintain the security of your accounts, and that your account information remains secure."
> Me: "Okay. Do you know if any additional security steps will need to be taken once it is re-enabled?"
> Fidelity: "Not as of right now. We have not been advised that there should be any additional measures taken once re-enabled."

Putting two and two together, it appears that requiring ':443' in the URL for a few days constitutes "a proactive step to maintain the security of your accounts". I think my favorite part is that they have pulled this exact same stunt enough in the past that other folks figured out how to add ':443' to get around it. Brilliant.

Anyway, I've discovered that some folks successfully keep the Fidelity URL *always* containing ':443', even when Fidelity hasn't enabled "super sekrit :443 mode". As per this link, 'pocketsense' and 'hleofxquotes' projects reportedly do this without incident: https://infinitekind.tenderapp.com/discussions/online-banking/17410-error-downloading-from-fidelity. I don't think either of them do the profile lookup step, though. I'm not going to advocate for adding a kludge just for the few days a year that Fidelity does this, though, so this can be closed unless you feel compelled.

**Comment by csingley** [comment]
Weeeelllll....  let me know if some action is needed here.  Thanks.

**Comment by aclindsa** [comment]
FYI, for anyone who encounters this issue from seeing a similar error recently, it appears that Fidelity is doing the same thing again this year. I have observed the same behavior outlined above since November 19, 2021 (and it has not stopped yet as of today, November 28th, 2021).

**Comment by zhou13** [comment]
I am using `ofxtool` and my fidelity stops working recently. I tried setting the url to `https://ofx.fidelity.com:443/ftgw/OFX/clients/download` but the error is the same. Is this still a valid workaround?

**Comment by aclindsa** [comment]
> Is this still a valid workaround?

I just tried with `ofxgo` a minute ago and it works for me (separate project). I have not tried the :443 workaround with `ofxtools` recently, but IIRC, we did not make the code changes necessary for `ofxtools` to ignore the URL returned from the profile lookup step. Fidelity returns non-443 URLs if you do the profile lookup before querying for transactions, so I suspect `ofxtools` is not actually making the transaction request using `:443` as you expect. @csingley can confirm.

**Comment by csingley** [comment]
>  IIRC, we did not make the code changes necessary for ofxtools to ignore the URL returned from the profile lookup step.

沒錯

> I suspect ofxtools is not actually making the transaction request using :443 as you expect.

正確

I should probably rename `ofxtools.Client.OFXClient.url` to `profile_url` to more accurately reflect its current usage.

If indeed it is the case that Fidelity is publishing download URLs that they won't honor, that's very disappointing.  If it can be shown that they will consistently honor another URL (i.e. the :443 hack), I'd be willing to consider modifying the `OFXClient` to provide the option to skip all that `_get_service_urls()` rigmarole.

**Comment by aclindsa** [comment]
> If it can be shown that they will consistently honor another URL (i.e. the :443 hack), I'd be willing to consider modifying the `OFXClient` to provide the option to skip all that `_get_service_urls()` rigmarole.

I actually already had such a patch laying around, so I rebased it and pushed it here: https://github.com/aclindsa/ofxtools/tree/skip_profile

Unfortunately, although I confirmed the URL was now what I expected just before making the request, this commit does not appear to allow me to successfully retrieve Fidelity OFX for my account. I don't know that I have time right now to investigate further.

**Comment by csingley** [comment]
> I don't know that I have time right now to investigate further.

Heard that!  Gettin hectic

Would it be easy for you to perform the converse experiment?  i.e. use `ofxgo` to download a statement from Fido w/out the workaround of explicitly including the TCP port in the URL.

**Comment by aclindsa** [comment]
> Would it be easy for you to perform the converse experiment? i.e. use `ofxgo` to download a statement from Fido w/out the workaround of explicitly including the TCP port in the URL.

Hah! Unfortunately, no, because `ofxgo` has never supported actually querying the real request URLs via profile lookups.

**Comment by csingley** [comment]
Sorry, I must not be being clear.  Can `ofxgo` now successfully download statements from `https://ofx.fidelity.com/ftgw/OFX/clients/download` (i.e. without appending :443 to the URL)

**Comment by aclindsa** [comment]
> Sorry, I must not be being clear. Can `ofxgo` now successfully download statements from `https://ofx.fidelity.com/ftgw/OFX/clients/download` (i.e. without appending :443 to the URL)

Ah, I see. This was the perfect question. It turns out that :443 is *not* required, so we are looking at a separate issue. Thank you for keeping me honest.

**Comment by csingley** [comment]
I need to figure out what `requests` and `ofxgo` are doing right but `ofxtools` is doing wrong.  Presumably at the level of TLS and/or HTTP.  First thing to check would be the HTTP headers; I imagine `requests` and `ofxtools` should be using the same implementation of SSL.

**Comment by csingley** [comment]
I've been too busy huffing epoxy to recall the excellent work of @mbafford on this problem in #140.

I'm closing this issue in favor of that one.
