### ISSUE TITLE
BBVA USA issue

### ISSUE THREAD

**Issue by paraviz02** [csingley/ofxtools#118]
Hello there -- we've had quite a bit of luck attempting to retrieve OFX v2 data from our financial institutions, but now dealing with the last one, BBVA USA, and it's getting a bit frustrating. The general issue here is that the request seems to be malformed or wrong coming from ofxget in a way that the remote endpoint does not understand.

I've tried playing with some of the scripts involved, modifying certain values and going at it with a trial-and-error approach (I have minimal understanding of Python) ... To no avail; only an HTML page with "Error" as the title and some random strings and javascript is returned.

At this point, when running ofxget with --dryrun and verbose just trying to receive the profile, everything except the cookies (shown below) and I would imagine the user agent seems to match.

I'm thinking the answer is going to be simple, or flat out impossible.  But it's worth a go.

Here are the settings I am using in ofxget:
```
url = https://olb.bbvausa.com/ofx/api/request
org = BBVA USA
fid = 2201
version = 102
appear = 2700
appid = QBW
unclosedelements = true
pretty = true
nonewfileuid = true
```

And I have modified some of the script to change (as I couldn't figure out how to do it otherwise):
> - CLIENTROUTING from NONE to MSGSET
> - DTPROFUP to 19900101
> - CHARSET from NONE to 1252
> - Remove all indents/whitespace formatting from pretty = true

Below are the requests/responses when using *QuickBooks* to make a successful connection:

Profile request
Request/headers:
```
POST /ofx/api/request HTTP/1.1
Accept: */*
Content-Type: application/x-ofx
Date: Thu, 04 Feb 2021 21:30:32 GMT
User-Agent: InetClntApp/3.0
Host: olb.bbvausa.com
Content-Length: 579
Connection: Keep-Alive
Cache-Control: no-cache
Cookie: True-Client-IP=1.2.3.4; bm_sz=15D0EE238E6C2DE9B0A49B070FF76421~YAAQbag8F0STZD13AQAActPZbgqJ5xe84BZmDXkK6JkuRCbifqdlgjWLtpbNYoPwj4KWXvq2Vr+F9hnq2CdMmRvEscBbGyaKHQMl57BZMLuPu15abGBSKzjgb4hGGg1poRTcMr+IM8pDOrMl1iofS1xku3x6T7vlFtR0knx+Fr+l3ul561uzZcxrrAPlZ/h2aw==; _abck=F0BA49A3F6CE93F5E87C5EADA8CBF20B~-1~YAAQbag8F0WTZD13AQAActPZbgVudjlqF8IYyVGUyCH+RwvulxaOLo7zuk7moITGMUS7+vxK6binr35ZpMjGYeq1TUmVN+SldgIkF7YmhrB7yov4AcmGvURl4ZTng4WMy/WpWZdcStGppRF1yG5k3UmxMuG/fHjseNVgs0G9c9WupVGxnIZiquX8dytNb2La/cKqi+ocovA26U1BTFSzl3qyMULWw6PaQyjz4J86qzyGLTNTfu5vG6MH0yls2rSmNXnkJpC2tzcuSIhlU1scD5mzZv2E/7c4UAD8W3mrVvUL1uxMbb9TW/YZNA==~-1~-1~-1; dtCookie=v_4_srv_1_sn_E6B8A68437A5699BA16BA2892DD641B0_perc_100000_ol_0_mul_1; JSESSIONID=0001R24sw54l4Jkz3b88GZSyGYE:VAFVNNVB8
```

POST:
```
OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:NONE

<OFX>
<SIGNONMSGSRQV1>
<SONRQ>
<DTCLIENT>20210204133032.123[-8:PST]
<USERID>anonymous00000000000000000000000
<USERPASS>anonymous00000000000000000000000
<GENUSERKEY>N
<LANGUAGE>ENG
<FI>
<ORG>BBVA USA
<FID>2201
</FI>
<APPID>QBW  
<APPVER>3000
</SONRQ>
</SIGNONMSGSRQV1>
<PROFMSGSRQV1>
<PROFTRNRQ>
<TRNUID>1BB84780-7DBE-1000-A461-E568CBA30026
<PROFRQ>
<CLIENTROUTING>MSGSET
<DTPROFUP>19900101
</PROFRQ>
</PROFTRNRQ>
</PROFMSGSRQV1>
</OFX>
```

**Comment by csingley** [comment]
Thanks for the good bug report.  I'd like to get BBVA's connection information sorted out, because our FI database predates their M&A spree in the US market.

So I patched the source in a couple places, and did this:
```
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from datetime import datetime, timedelta, timezone

In [2]: pst = timezone(-timedelta(hours=8), name="PST")

In [3]: from ofxtools import OFXClient

In [4]: client = OFXClient(url="https://olb.bbvausa.com/ofx/api/request", org="BBVA USA", fid="2201", version=102, appid="QBW", appver="3000", close_elements=False,
   ...:                    prettyprint=True)

In [5]: client.dtclient = lambda: datetime.now(pst)

In [6]: resp = client._request_profile(dtprofup=datetime(1990, 1, 1, tzinfo=pst), gen_newfileuid=False, dryrun=True)

In [7]: resp.readlines()
Out[7]: 
[b'OFXHEADER:100\r\n',
 b'DATA:OFXSGML\r\n',
 b'VERSION:102\r\n',
 b'SECURITY:NONE\r\n',
 b'ENCODING:USASCII\r\n',
 b'CHARSET:1252\r\n',
 b'COMPRESSION:NONE\r\n',
 b'OLDFILEUID:NONE\r\n',
 b'NEWFILEUID:NONE\r\n',
 b'\r\n',
 b'<OFX>\n',
 b'<SIGNONMSGSRQV1>\n',
 b'  <SONRQ>\n',
 b'  <DTCLIENT>20210208093934.840[-8:PST]\n',
 b'      <USERID>anonymous00000000000000000000000\n',
 b'      <USERPASS>anonymous00000000000000000000000\n',
 b'      <LANGUAGE>ENG\n',
 b'      <FI>\n',
 b'      <ORG>BBVA USA\n',
 b'        <FID>2201\n',
 b'      </FI>\n',
 b'      <APPID>QBW\n',
 b'      <APPVER>3000\n',
 b'    </SONRQ>\n',
 b'  </SIGNONMSGSRQV1>\n',
 b'  <PROFMSGSRQV1>\n',
 b'<PROFTRNRQ>\n',
 b'  <TRNUID>A5A4F9A5-8D2F-4AAF-A810-433BFAD66944\n',
 b'      <PROFRQ>\n',
 b'    <CLIENTROUTING>MSGSET\n',
 b'        <DTPROFUP>19900101000000.000[-8:PST]\n',
 b'      </PROFRQ>\n',
 b'    </PROFTRNRQ>\n',
 b'  </PROFMSGSRQV1>\n',
 b'</OFX>\n']

In [8]: resp = client._request_profile(dtprofup=datetime(1990, 1, 1, tzinfo=pst), gen_newfileuid=False)
re
In [9]: resp.readlines()
Out[9]: 
[b'<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>\n',
 b'An error occurred while processing your request.<p>\n',
 b'Reference&#32;&#35;30&#46;8433ca17&#46;1612805986&#46;10b3f412\n',
 b'<script type="text/javascript" >var _cf = _cf || []; _cf.push([\'_setFsp\', true]);  _cf.push([\'_setBm\', true]);  _cf.push([\'_setAu\', \'/webcontent/af14a14cui206ede8de96a8770e74c\']); </script><script type="text/javascript"  src="/webcontent/af14a14cui206ede8de96a8770e74c"></script></BODY></HTML>\n']
```
So this is really getting down to very minor differences.... the format of `DTPROFUP` and the whitespace in the pretty printing.  The HTTP wrapper looks the same.

Could it be the newline character used by Quickbooks?  Are they perhaps sending `\r\n` for newlines, where we use `\n`, and their parser is relying on that behavior?

**Comment by paraviz02** [comment]
@csingley - I have the contents of the exchange in hex. The new lines in the request is exactly as how you have show there.

And I'm not sure if it matters, but they have no indentation at all. So it's essentially pretty print functioning as \r\n only, and not making it pretty.

The only other difference I can see in the request is that they are using only the YYYYmmdd for the DTPROFUP field.

Hmm wait I take that back, there are two white spaces after QBW in the <APPID>. I couldn't imagine why that would matter, unless they are explicitly looking for an exact 5-character string?

**Comment by csingley** [comment]
Would you do me a favor and try to send the contents of that Quickbooks profile request verbatim (including the OFX header) via `curl`, or whatever your favorite HTTP utility might be?

I would like to verify that it is actually possible for anything other than Quickbooks to connect by `POST`ing that data.

**Comment by paraviz02** [comment]
Well, not saying I'm a curl pro, but I had been trying to do that last week, and when I'd expect at least a response of some sort (error, success, 500 error, etc.) it was just sitting there and no data was received at all. That was in shell, I'll try it through PHP and let you know.

**Comment by csingley** [comment]
You could also try attaching it here as a file, so I can easily feed it to python and/or curl without worrying about Github mangling the whitespace.

**Comment by paraviz02** [comment]
Good idea, stand by. My apologies for the delayed response ... It's been a wild day.

I also have the HTTPS requests/responses when creating the connection from QB to BBVA, if that can be of any help.

[post.txt](https://github.com/csingley/ofxtools/files/5947638/post.txt)

**Comment by paraviz02** [comment]
Also, when I tried with curl in PHP, I got the same result.
```
<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>
An error occurred while processing your request.<p>
Reference&#32;&#35;30&#46;553c7c68&#46;1612822690&#46;8706e429
<script type="text/javascript" >var _cf = _cf || []; _cf.push(['_setFsp', true]);  _cf.push(['_setBm', true]);  _cf.push(['_setAu', '/webcontent/af14a14cui206ede8de96a8770e74c']); </script><script type="text/javascript"  src="/webcontent/af14a14cui206ede8de96a8770e74c"></script></BODY></HTML>
```

**Comment by csingley** [comment]
I tried it with the Cookies set above - no dice:

```
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: with open("post.txt", "rb") as f:
   ...:     request = f.read()
   ...: 

In [2]: request
Out[2]: b'OFXHEADER:100\r\nDATA:OFXSGML\r\nVERSION:102\r\nSECURITY:NONE\r\nENCODING:USASCII\r\nCHARSET:1252\r\nCOMPRESSION:NONE\r\nOLDFILEUID:NONE\r\nNEWFILEUID:NONE\r\n\r\n<OFX>\n<SIGNONMSGSRQV1>\n<SONRQ>\n<DTCLIENT>20210208160243000-8:PST]\n<USERID>anonymous00000000000000000000000\n<USERPASS>anonymous00000000000000000000000\n<GENUSERKEY>N\n<LANGUAGE>ENG\n<FI>\n<ORG>BBVA USA\n<FID>2201\n</FI>\n<APPID>QBW  \n<APPVER>3000\n</SONRQ>\n</SIGNONMSGSRQV1>\n<PROFMSGSRQV1>\n<PROFTRNRQ>\n<TRNUID>0acffebb-3377-48e0-9fd0-29329de78c5d\n<PROFRQ>\n<CLIENTROUTING>MSGSET\n<DTPROFUP>19900101\n</PROFRQ>\n</PROFTRNRQ>\n</PROFMSGSRQV1>\n</OFX>\n'

In [3]: import urllib

In [4]: req = urllib.request.Request("https://olb.bbvausa.com/ofx/api/request", method="POST", data=request, headers={"User-Agent": "InetClntApp/3.0", "Content-type":
   ...: "application/x-ofx", "Accept": "*/*", "Cookie": "True-Client-IP=1.2.3.4; bm_sz=15D0EE238E6C2DE9B0A49B070FF76421~YAAQbag8F0STZD13AQAActPZbgqJ5xe84BZmDXkK6JkuRCb
   ...: ifqdlgjWLtpbNYoPwj4KWXvq2Vr+F9hnq2CdMmRvEscBbGyaKHQMl57BZMLuPu15abGBSKzjgb4hGGg1poRTcMr+IM8pDOrMl1iofS1xku3x6T7vlFtR0knx+Fr+l3ul561uzZcxrrAPlZ/h2aw==; _abck=F0
   ...: BA49A3F6CE93F5E87C5EADA8CBF20B~-1~YAAQbag8F0WTZD13AQAActPZbgVudjlqF8IYyVGUyCH+RwvulxaOLo7zuk7moITGMUS7+vxK6binr35ZpMjGYeq1TUmVN+SldgIkF7YmhrB7yov4AcmGvURl4ZTng
   ...: 4WMy/WpWZdcStGppRF1yG5k3UmxMuG/fHjseNVgs0G9c9WupVGxnIZiquX8dytNb2La/cKqi+ocovA26U1BTFSzl3qyMULWw6PaQyjz4J86qzyGLTNTfu5vG6MH0yls2rSmNXnkJpC2tzcuSIhlU1scD5mzZv2E
   ...: /7c4UAD8W3mrVvUL1uxMbb9TW/YZNA==~-1~-1~-1; dtCookie=v_4_srv_1_sn_E6B8A68437A5699BA16BA2892DD641B0_perc_100000_ol_0_mul_1; JSESSIONID=0001R24sw54l4Jkz3b88GZSyGY
   ...: E:VAFVNNVB8"})

In [5]: response = urllib.request.urlopen(req, timeout=10.0)

In [6]: response.readlines()
Out[6]: 
[b'<HTML><HEAD><TITLE>Error</TITLE>\n',
 b'                    <script>var w=window;if(w.performance||w.mozPerformance||w.msPerformance||w.webkitPerformance){var d=document;AKSB=w.AKSB||{},AKSB.q=AKSB.q||[],AKSB.mark=AKSB.mark||function(e,_){AKSB.q.push(["mark",e,_||(new Date).getTime()])},AKSB.measure=AKSB.measure||function(e,_,t){AKSB.q.push(["measure",e,_,t||(new Date).getTime()])},AKSB.done=AKSB.done||function(e){AKSB.q.push(["done",e])},AKSB.mark("firstbyte",(new Date).getTime()),AKSB.prof={custid:"858443",ustr:"",originlat:"0",clientrtt:"123",ghostip:"172.232.5.61",ipv6:false,pct:"10",clientip:"104.13.176.246",requestid:"49880901",region:"35531",protocol:"",blver:14,akM:"a",akN:"ae",akTT:"O",akTX:"1",akTI:"49880901",ai:"225198",ra:"false",pmgn:"",pmgi:"",pmp:"",qc:""},function(e){var _=d.createElement("script");_.async="async",_.src=e;var t=d.getElementsByTagName("script"),t=t[t.length-1];t.parentNode.insertBefore(_,t)}(("https:"===d.location.protocol?"https:":"http:")+"//ds-aksb-a.akamaihd.net/aksb.min.js")}</script>\n',
 b'                    </HEAD><BODY>\n',
 b'An error occurred while processing your request.<p>\n',
 b'Reference&#32;&#35;30&#46;5732c717&#46;1612832020&#46;d67a149\n',
 b'<script type="text/javascript" >var _cf = _cf || []; _cf.push([\'_setFsp\', true]);  _cf.push([\'_setBm\', true]);  _cf.push([\'_setAu\', \'/webcontent/af14a14cui206ede8de96a8770e74c\']); </script><script type="text/javascript"  src="/webcontent/af14a14cui206ede8de96a8770e74c"></script></BODY></HTML>\n']
```

**Comment by paraviz02** [comment]
@csingley is it possible that QuickBooks contacts Intuit, negotiates some token or access code for a given bank, and then Intuit is used as a central auth location for the client and bank?

I'm going to go through the raw packets tomorrow and see if I can identify if anything from Intuit that may be required to request profile or statements from BBVA. Because it seems rather odd that so many cookies were sent in the initial request.

I can also make the requests anonymous (ie, removing my username/password to BBVA) and present the request/response here?

**Comment by paraviz02** [comment]
Also, just a side note, the "True-Client-IP" header might possibly be a red flag, unless your IP is actually 1.2.3.4 ;-)

I'll update with more tomorrow after I review all the request/response traffic to both Intuit and BBVA.

**Comment by paraviz02** [comment]
And to put it bluntly, if BBVA thinks it is a good idea to limit their customers' digital access to Intuit products, then I think it is a good idea to limit my customers' access to non-BBVA services. Ha ha ...

Take care, @csingley, have a good evening.

**Comment by csingley** [comment]
So I've actually got an account at BBVA.  Logging in, I do Service Center > Quicken and QuickBooks Access Self Service > Register New Access.

The webpage shows this:

> Registration Request Received

> Please note: Within 24 hours, you must connect to your BBVA Online Banking using Quicken or QuickBooks to complete the registration process.

This may be part of the answer here.

**Comment by paraviz02** [comment]
@csingley yes, I went and enabled that, attempted to run acctinfo using ofxget, but it is angry still.

You'd think that simply retrieving the profile information would work though. Looking at the QB transactions with BBVA, it seems like they requested the profile information, then went to the account info, then pulled the rest of the data.

I've got a bit of a wild morning, but will analyze the requests/responses to see if I can identify anything suspect on the QB/Intuit side of things. I'm hoping that they haven't spoiled it for everyone ...

I'll update later on today. Cheers.

**Comment by csingley** [comment]
It's entirely possible that enabling that switch opens up a window for you to register a `CLIENTUID`, which you'll need to send consistently thereafter.  This extra auth mechanism is in the OFX spec, and the BBVA website explicitly mentions non-Quicken applications "using the Quicken [i.e. OFX] interface".  So I'd say this is the first thing to check.  Enable the registration window; generate a UUID; store that in the `clientuid` setting in your `ofxget.cfg` (or wherever else you feed it to the OFX client).

Quicken does indeed do `PROFRQ` before any kind of `SMTRQ`; this flow is in the OFX spec too.

BBVA should be honoring anonymous profile requests even from non-authenticated users, but if they're going out-of-band with their web registration technique, it's not surprising if they screwed this up.  Push past this with optimism, and try to get a STMTRQ with a CLIENTUID set.

**Comment by paraviz02** [comment]
@csingley I didn't get a chance to go through the req/resp today. It's on my list for tomorrow.

But for the record, here's the response when requesting profile information.
[profile.txt](https://github.com/csingley/ofxtools/files/5955181/profile.txt)

**Comment by csingley** [comment]
Did you notice this part in the `PROFRS`?
```
<CLIENTUIDREQ>Y
```

**Comment by paraviz02** [comment]
I did, yes. Though I know nothing of OFX protocol so it might as well be a chicken sandwich.

I was trying to replicate the transaction between QB to BBVA, but I’m more of a layman for these processes.

Still, it should be able to request the profile, no?

**Comment by csingley** [comment]
`CLIENTUIDREQ` is a very unique search string; there are only about two occurrences within the spec.

>2.5.1.1.1 Client Unique ID <CLIENTUID>
>OFX servers can require OFX clients to include a client ID in each signon request. This client ID should
>be unique to the installation of the client software, but the method that the ID is generated is left up to the
>client. The server can specify that this field is required using the <CLIENTUIDREQ> tag in the applicable
><SIGNONINFO> section of the profile. Servers should expect that users may connect via OFX from
>multiple locations and may need to associate more than one <CLIENTUID> value with their <USERID>.
>The client may make this value user discoverable, so that the user can register the client ID with financial
>institutions.

So this is what BBVA's OFX profile is announcing.  In combination with the "register new application" workflow mentioned on their website.... my guess is that if you open the registration window, then proceed log into their OFX server with `CLIENTUID` set in the signon, and the `CLIENTUID` is a new value not previously known to the server, then their server will remember it and subsequently authorize OFX logins bearing that token.

Chase Bank has an analogous auth workflow, although the details are a little different.

> Still, it should be able to request the profile, no?

This is what pisses me off.  Quickbooks is clearly succeeding with `PROFRQ`/`PROFRS` without any auth information (username, password, CLIENTUID).  I believe formatting differences have just about been ruled out in this ticket.  Really about the only place to hide is in the HTTP header cookies.

Perhaps, when you register a CLIENTUID and sign in, the returned response will contain cookies that you're supposed to store & return.

**Comment by csingley** [comment]
BTW, note that BBVA's OFX profile is announcing version 103, not 102... and 103 is required to use the `CLIENTUID` auth setup.

**Comment by paraviz02** [comment]
@csingley it was another mess of a day. You’re right about the version, though QB starts out by requesting 102 and then goes to 103 after. I tried with both, but it did not like either.

I still need to look at cookies and the whole process between QB and BBVA. Which I am going to try my hardest to prioritize tomorrow.

But it truly is weird QB can request an anonymous profile query and get a proper answer.

**Comment by paraviz02** [comment]
@csingley I've been looking at this a bit this afternoon (finally have some time). Here's the way it goes ...

First, the initial request includes the following two cookies, and I do not have any clue where they come from:
```
bm_sz | 15D0EE238E6C2DE9B0A49B070FF76421~YAAQbag8F0STZD13AQAActPZbgqJ5xe84BZmDXkK6JkuRCbifqdlgjWLtpbNYoPwj4KWXvq2Vr+F9hnq2CdMmRvEscBbGyaKHQMl57BZMLuPu15abGBSKzjgb4hGGg1poRTcMr+IM8pDOrMl1iofS1xku3x6T7vlFtR0knx+Fr+l3ul561uzZcxrrAPlZ/h2aw==
-- | --
_abck | F0BA49A3F6CE93F5E87C5EADA8CBF20B~-1~YAAQbag8F0WTZD13AQAActPZbgVudjlqF8IYyVGUyCH+RwvulxaOLo7zuk7moITGMUS7+vxK6binr35ZpMjGYeq1TUmVN+SldgIkF7YmhrB7yov4AcmGvURl4ZTng4WMy/WpWZdcStGppRF1yG5k3UmxMuG/fHjseNVgs0G9c9WupVGxnIZiquX8dytNb2La/cKqi+ocovA26U1BTFSzl3qyMULWw6PaQyjz4J86qzyGLTNTfu5vG6MH0yls2rSmNXnkJpC2tzcuSIhlU1scD5mzZv2E/7c4UAD8W3mrVvUL1uxMbb9TW/YZNA==~-1~-1~-1
```
The request is as follows:
[1-req.txt](https://github.com/csingley/ofxtools/files/5968844/1-req.txt)

Then we get the response:
[1-resp.txt](https://github.com/csingley/ofxtools/files/5968845/1-resp.txt)

They are also asking to set the following new cookies:
```
Set-Cookie: JSESSIONID=0001R24sw54l4Jkz3b88GZSyGYE:VAFVNNVB8; Path=/; HttpOnly
Set-Cookie: dtCookie=v_4_srv_1_sn_E6B8A68437A5699BA16BA2892DD641B0_perc_100000_ol_0_mul_1; Path=/; Domain=.bbvausa.com
Set-Cookie: True-Client-IP=108.226.35.139; secure
```

It then requests the profile again (receiving the same data).  Only difference is the UID and date/time.

From this point on, it seems that everything is good to go. It will then authenticate with the proper user/pass and go on to retrieve account information, etc. and maintains that same set of cookies through the whole transaction.

I've never seen the bm_sz or _abck cookies.  And I cannot find where they were generated or requested to be set.  But they were there from the first request to BBVA, and may have something to do with it?

I did not actually record any of the web traffic prior to opening QB.  But maybe that is something set when QB phones home (which it does many times, and sends account info, security questions, passwords, etc.).

With every request, it asks to set the cookie True-Client-IP with the originating client IP.

Does any of this info help identify something we may be missing?

**Comment by csingley** [comment]
Yeah I dunno.  If Quickbooks is able to get through, then it's not the case that your IP got thrown on a blacklist for too many bad connection attempts.

**Comment by paraviz02** [comment]
@csingley I've done a bit of research on those two cookies that are present during the first call to BBVA -- _abck and bm_sz.  It seems they are some sort of anti-bot verification.

https://www.akamai.com/us/en/products/security/bot-manager.jsp
https://security.stackexchange.com/questions/182895/anti-bot-javascript-library-identification

The _abck is labeled as Akamai Bot Manager - Security cookie, and it expires after 1 day. And bm_sz is labeled as Akamai bot manager / Fraud prevention and expires after each session.

Not really sure how these cookies are retrieved/generated, but QB doesn't seem to have an issue getting them before attempting to connect to BBVA. Trying to do a little more research on this ... But I'll bet this is the issue.

**Comment by paraviz02** [comment]
After looking into those two cookies a bit more, BBVA's main website asks for those cookies to be set upon the first request.  But I don't know enough about Python to know how to retrieve headers or add them into a request.  I can retrieve them in PHP using curl though.

The next response asks to set the JSESSIONID, dtCookie and True-Client-IP cookies.

All of this is a bit above my head.  If I wanted to generate these manually outside of the ofxget request, and then insert them to the ofxget request, how would I go about doing that?

**Comment by csingley** [comment]
I had been under the impression that using `urrlib.request.HTTPCookieProcessor` in`ofxtools.Client.OFXClient.download()` was supposed to take care of this sort of thing automatically.

But here I can only play Andy Kaufman to @rianhunter 's Mighty Mouse.

**Comment by paraviz02** [comment]
Would it be possible using ofxget to dump the request and response headers for debug purposes?  I'd be curious to know if it is indeed retrieving those.

When making a request to https://olb.bbvausa.com/ofx/api/request, those cookies are indeed requested to be set.

**Comment by rianhunter** [comment]
The most robust way to debug this issue would be to log exactly what Quicken is doing and what ofxtools is doing and look at the diff between the two.

ofxtools should be carrying cookies across the profile request to the statement request. I'm not sure if @csingley made it so that the profile request is done automatically but with the oldish version of ofxtools that I use, I have to explicitly do a profile request first. Are you doing the profile request first?

A great free tool that I use for debugging these types of issues is mitmproxy. I run mitmproxy on my Linux machine, then install the root certificate on my Windows PC and set my Windows PC's proxy settings accordingly. Then I go through a Quicken install and setup of my bank account. This will give you the entire Quicken request log.

**Comment by csingley** [comment]
>  I'm not sure if @csingley made it so that the profile request is done automatically

It is. This logic lives in `ofxtools.Client.OFXClient._get_service_urls()`, which is called by all the `request_*` methods except `request_profile()` itself.

**Comment by rianhunter** [comment]
> It is. This logic lives in `ofxtools.Client.OFXClient._get_service_urls()`, which is called by all the `request_*` methods except `request_profile()` itself.

Ah okay, then what I said is probably moot. There's a good chance it's the anti-bot detection but without the two request streams it's hard to tell. It's possible Quickbooks is making an out-of-band API call to retrieve some verification token that it uses in subsequent OFX requests as a cookie.

**Comment by paraviz02** [comment]
Yes, I have the requests/responses from QB.  Have gone through those, and the only thing that's different (that I can tell) is the two cookies (bm_sz and _abck) being included on the initial request to BBVA's endpoint.

I'm going to see if I can reproduce a successful profile request with PHP/curl.  I'll report back.

**Comment by rianhunter** [comment]
Hmm in the request log, what does QB do before making the initial request to BBVA's endpoint? It has to be getting those cookies from somewhere. If it's seemingly from nowhere, then maybe it's worth doing a fresh install of QB to rule out the possibility that it is caching that information from an earlier request.

**Comment by paraviz02** [comment]
@rianhunter yes, I thought about the cached request as well.

I actually ran it 3 separate times to get what I thought would be more complete logs of the requests, and only saved the last two.  It must have got the cookie the first time when I was not recording.

If manually creating the process using curl doesn't work, I'll try to re-record the web requests.

**Comment by paraviz02** [comment]
Well, I'm going to have to call my pops up again, who I use to get the QB requests. I cannot stand Intuit products ... So don't have any copy of my own. ;-)

After banging my face into the wall, the best I'm able to get is "An error occurred while processing your request."

HOWEVER, in BBVA's documentation regarding setting up QB or Quicken, it states: "You will also use these steps to resister connections with other financial management programs that use the same connection as Quicken. **That includes but is not limited to Mint and iBank.**"

So I feel like there is a light at the end of the tunnel.  And I don't believe that Intuit is ruining the party.  It's just what on earth could be the issue?!

**Comment by paraviz02** [comment]
Actually ... Is there a way that we can skip the profile request and go straight to statements or account info?

**Comment by paraviz02** [comment]
When trying to add BBVA to ofxhome.com, it gets angry too. So BBVA could be a bit like the [Vanguard issue](https://github.com/csingley/ofxtools/issues/94) brought up a few months back.

It would be nice to know the reasons behind why anyone would deviate from any standards or specifications ...

**Comment by csingley** [comment]
>  Is there a way that we can skip the profile request and go straight to statements or account info?

Not at present.  I made the decision to imitate Quicken, follow the spec, and always do the `PROFRQ` ahead of `SMTRQ` `ACCTINFORQ` et al.  It would be a reasonable request for a feature enhancement though; it's what we used to do until recently.  You can still get this behavior by downgrading... perhaps `c77df16ea6e082c5fe5917230393a0322d97c90e` is the commit you'd want, or a little earlier (i.e. after rianhunter handled cookies, but before I started getting all prescriptivist about the process).

But as other users have pointed out, you can also just use `ofxget --dryrun` to dump OFX requests to hand off to other shell tools like `curl`.  It seems a somewhat popular workflow for debugging.

**Comment by paraviz02** [comment]
Yes, and you were correct to follow the spec.

BBVA is nuts ... Even considering normal exports from the web UI, there's not even a way to do that without a ton of pain and suffering.  Gotta hand it to Intuit, they must have the magical touch.

**Comment by csingley** [comment]
> When trying to add BBVA to ofxhome.com, it gets angry too.

You might try emailing Jesse.  I plan to add BBVA to the `ofxtools` database of FIs, but I really would like to get at least one successful response first!  I appreciate your persistence.

> It would be nice to know the reasons behind why anyone would deviate from any standards or specifications ...

The general answer here is "security", combined with "near-monopoly market share by a single implementation".

Now that Intuit has sold off Quicken to a PE shop, the situation is in the process of getting much worse.  After harvesting the low-hanging fruit by strong-arming everyone to a subscription model, the new now owners seem to have stalled all security enhancements to the OFX protocol.  Instead they're grafting OAuth-type AAA mechanisms onto a new protocol (FDX) intended to replace OFX, and which will not be an open standard.

It's enough to make the baby JWZ cry.  Or Jim Clark, whatever.

It's nothing but a headache for the banks.  All they can think about is potential liability incurred by this ancient, creaking, insecure protocol.  Capital One (no dummies when it comes to IT) shut down all their OFX servers years ago, and never turned them back on.

**Comment by paraviz02** [comment]
@csingley haha, yes this all makes me sad.

The even sadder reality for all these places is that the OFX data is no less safe than the user's web login to the bank's portal.  There would be an angry mob with pitchforks and torches if their online banking was made any more difficult (and secure) than it is now.

Is Jesse at OFXHome.com?

**Comment by csingley** [comment]
> OFX Home is developed and maintained by Jesse Liesch (email: my first name at this address)

http://www.ofxhome.com/index.php/home/about

**Comment by paraviz02** [comment]
Thanks @csingley ... It's been a bear of a week, so will reach out soon.
