### ISSUE TITLE
Tests failing due to DBSession

### ISSUE THREAD

**Issue by PierreRochard** [csingley/ofxtools#14]
I rebased and ran into import problems with DBSession, tests are failing on master:

<pre>
(venv) Pierres-MacBook-Pro-2:ofxtools-upstream Rochard$ make test
coverage erase
nosetests -dsv --with-yanc --with-coverage --cover-package ofxtools tests/*.py
test_account_type_checking (test_alchemy.AlchemyTestCase) ... ERROR
test_account_type_investment (test_alchemy.AlchemyTestCase) ... ERROR
test_euro_decimal_separator (test_alchemy.AlchemyTestCase) ... ERROR
testInvalid (test_header.OFXHeaderV1TestCase) ... ok
testStr (test_header.OFXHeaderV1TestCase) ... ok
testStrip (test_header.OFXHeaderV1TestCase) ... ok
testValid (test_header.OFXHeaderV1TestCase) ... ok
testInvalid (test_header.OFXHeaderV2TestCase) ... ok
testStr (test_header.OFXHeaderV2TestCase) ... ok
testStrip (test_header.OFXHeaderV2TestCase) ... ok
testValid (test_header.OFXHeaderV2TestCase) ... ok
testConvert (test_models.AvailbalTestCase) ... ok
Adding an extra Element not in the spec makes Aggregate.__init__() ... ok
testOptional (test_models.AvailbalTestCase) ... ok
testRequired (test_models.AvailbalTestCase) ... ok
testConvert (test_models.BalTestCase) ... ok
Adding an extra Element not in the spec makes Aggregate.__init__() ... ok
testOneOf (test_models.BalTestCase) ... ok
testOptional (test_models.BalTestCase) ... ok
testRequired (test_models.BalTestCase) ... ok
testConvert (test_models.BankacctfromTestCase) ... ok
Adding an extra Element not in the spec makes Aggregate.__init__() ... ok
testOneOf (test_models.BankacctfromTestCase) ... ok
testOptional (test_models.BankacctfromTestCase) ... ok
testRequired (test_models.BankacctfromTestCase) ... ok
testConvert (test_models.CCacctfromTestCase) ... ok
Adding an extra Element not in the spec makes Aggregate.__init__() ... ok
testOptional (test_models.CCacctfromTestCase) ... ok
testRequired (test_models.CCacctfromTestCase) ... ok
testConvert (test_models.DebtinfoTestCase) ... ok
Adding an extra Element not in the spec makes Aggregate.__init__() ... ok
testOneOf (test_models.DebtinfoTestCase) ... ok
testOptional (test_models.DebtinfoTestCase) ... ok
testRequired (test_models.DebtinfoTestCase) ... ok
testConvert (test_models.InvacctfromTestCase) ... ok
Adding an extra Element not in the spec makes Aggregate.__init__() ... ok
testOptional (test_models.InvacctfromTestCase) ... ok
testRequired (test_models.InvacctfromTestCase) ... ok
testConvert (test_models.InvbalTestCase) ... ok
Adding an extra Element not in the spec makes Aggregate.__init__() ... ok
testOptional (test_models.InvbalTestCase) ... ok
testRequired (test_models.InvbalTestCase) ... ok
testConvert (test_models.LedgerbalTestCase) ... ok
Adding an extra Element not in the spec makes Aggregate.__init__() ... ok
testOptional (test_models.LedgerbalTestCase) ... ok
testRequired (test_models.LedgerbalTestCase) ... ok
testConvert (test_models.MfinfoTestCase) ... ok
Adding an extra Element not in the spec makes Aggregate.__init__() ... ok
testOneOf (test_models.MfinfoTestCase) ... ok
testOptional (test_models.MfinfoTestCase) ... ok
testRequired (test_models.MfinfoTestCase) ... ok
testConvert (test_models.OptinfoTestCase) ... ok
Adding an extra Element not in the spec makes Aggregate.__init__() ... ok
testOptional (test_models.OptinfoTestCase) ... ok
testRequired (test_models.OptinfoTestCase) ... ok
testConvert (test_models.OtherinfoTestCase) ... ok
Adding an extra Element not in the spec makes Aggregate.__init__() ... ok
testOptional (test_models.OtherinfoTestCase) ... ok
testRequired (test_models.OtherinfoTestCase) ... ok
testConvert (test_models.SonrsTestCase) ... ok
Adding an extra Element not in the spec makes Aggregate.__init__() ... ok
testOneOf (test_models.SonrsTestCase) ... ok
testOptional (test_models.SonrsTestCase) ... ok
testRequired (test_models.SonrsTestCase) ... ok
testConvert (test_models.StockinfoTestCase) ... ok
Adding an extra Element not in the spec makes Aggregate.__init__() ... ok
testOptional (test_models.StockinfoTestCase) ... ok
testRequired (test_models.StockinfoTestCase) ... ok
test_account_type_checking (test_parser.ParserTestCase) ... ok
test_account_type_investment (test_parser.ParserTestCase) ... ok
test_euro_decimal_separator (test_parser.ParserTestCase) ... ok
test_flatten (test_parser.TreeBuilderTestCase) ... ok
test_parse (test_parser.TreeBuilderTestCase) ... ok
test_convert (test_types.BoolTestCase) ... ok
test_optional (test_types.BoolTestCase) ... ok
test_required (test_types.BoolTestCase) ... ok
test_unconvert (test_types.BoolTestCase) ... ok
test_convert (test_types.DateTimeTestCase) ... ok
test_illegal (test_types.DateTimeTestCase) ... ok
test_optional (test_types.DateTimeTestCase) ... ok
test_required (test_types.DateTimeTestCase) ... ok
test_convert (test_types.DecimalTestCase) ... ok
test_euro_decimal_separator (test_types.DecimalTestCase) ... ok
test_illegal (test_types.DecimalTestCase) ... ok
test_optional (test_types.DecimalTestCase) ... ok
test_precision (test_types.DecimalTestCase) ... ok
test_required (test_types.DecimalTestCase) ... ok
test_convert (test_types.IntegerTestCase) ... ok
test_illegal (test_types.IntegerTestCase) ... ok
test_max_length (test_types.IntegerTestCase) ... ok
test_optional (test_types.IntegerTestCase) ... ok
test_required (test_types.IntegerTestCase) ... ok
test_convert (test_types.OneOfTestCase) ... ok
test_optional (test_types.OneOfTestCase) ... ok
test_required (test_types.OneOfTestCase) ... ok
test_convert (test_types.StringTestCase) ... ok
test_empty_string (test_types.StringTestCase) ... ok
test_max_length (test_types.StringTestCase) ... ok
test_optional (test_types.StringTestCase) ... ok
test_required (test_types.StringTestCase) ... ok

======================================================================
ERROR: test_account_type_checking (test_alchemy.AlchemyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Rochard/src/ofxtools-upstream/tests/test_alchemy.py", line 65, in test_account_type_checking
    ofx_to_database(filename)
  File "/Users/Rochard/src/ofxtools-upstream/tests/test_alchemy.py", line 44, in ofx_to_database
    parser.instantiate(DBSession)
TypeError: instantiate() takes 1 positional argument but 2 were given

======================================================================
ERROR: test_account_type_investment (test_alchemy.AlchemyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Rochard/src/ofxtools-upstream/tests/test_alchemy.py", line 75, in test_account_type_investment
    ofx_to_database(filename)
  File "/Users/Rochard/src/ofxtools-upstream/tests/test_alchemy.py", line 44, in ofx_to_database
    parser.instantiate(DBSession)
TypeError: instantiate() takes 1 positional argument but 2 were given

======================================================================
ERROR: test_euro_decimal_separator (test_alchemy.AlchemyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Rochard/src/ofxtools-upstream/tests/test_alchemy.py", line 70, in test_euro_decimal_separator
    ofx_to_database(filename)
  File "/Users/Rochard/src/ofxtools-upstream/tests/test_alchemy.py", line 44, in ofx_to_database
    parser.instantiate(DBSession)
TypeError: instantiate() takes 1 positional argument but 2 were given

Name                              Stmts   Miss  Cover
-----------------------------------------------------
ofxtools/Client.py                  269    201    25%
ofxtools/Parser.py                   98     28    71%
ofxtools/Response.py                113     19    83%
ofxtools/Types.py                   170     20    88%
ofxtools.py                           2      0   100%
ofxtools/header.py                   89     10    89%
ofxtools/lib.py                      12      0   100%
ofxtools/models.py                  378      3    99%
ofxtools/ofxalchemy/Parser.py       240    192    20%
ofxtools/ofxalchemy/Types.py         49     24    51%
ofxtools/ofxalchemy.py                2      0   100%
ofxtools/ofxalchemy/database.py      54     29    46%
ofxtools/ofxalchemy/models.py       371      1    99%
ofxtools/utils.py                    98     77    21%
-----------------------------------------------------
TOTAL                              1945    604    69%
----------------------------------------------------------------------
Ran 100 tests in 1.118s

FAILED (errors=3)
make: *** [test] Error 1
</pre>

Are you actively working on resolving this or would you advise I take the initiative in resolving? I completely understand if it's the latter, I really like this library but don't want to stress you out :)

**Comment by csingley** [comment]
The problem here is that I refactored all the ofxalchemy database-management logic without updating the relevant tetsts, because I suck at releasing software.

All that business about passing DBSession in to ofxalchemy.Parser methods is now gone.  Instead, just import ofxalchemy.database.Session and use that, or else use the query property on each of the ofxalchemy.models classes (e.g. SECINFO.query.filter_by(uniqueidtype='CUSIP', uniqueid='DEADBEEF').one())  This is just much better all around, and the tests don't yet reflect this syntax.

I'll fix these tests; I know just what the problem is.  However, you are entirely welcome to contribute tests, because the state of ofxtools testing is very poor indeed and I don't have a great deal of time to give it the attention it deserves.

**Comment by csingley** [comment]
Here you go

[ada8221](https://github.com/csingley/ofxtools/commit/ada82219e69e2ce3c1121ff37f85a4ede41d51a5)
