### ISSUE TITLE
Getting historical investment statement with ofxget --asof

### ISSUE THREAD

**Issue by vitaliknet** [csingley/ofxtools#149]
Trying to download historical position snapshot using ofxget "--asof" param, but am getting the current list of positions instead. Observing the same behavior with  prudential and fidelity.
 
ofxget stmt prudential -i ACCOUNT -u  USERNAME --asof 20220202 -v -v -v 

Request has "<INCPOS><DTASOF>20220202000000.000[+0:UTC]</DTASOF><INCLUDE>Y</INCLUDE></INCPOS>"
Response comes back with "<INVSTMTRS><DTASOF>20220213104227.710[-5:EST]</DTASOF>"

Do I misunderstand the purpose of "--asof" or perhaps they just ignore it?

**Comment by csingley** [comment]
Never seen FI that honored it.

**Comment by vitaliknet** [comment]
> Never seen FI that honored it.

Not too surprising. Thanks!
