### ISSUE TITLE
OFXHome Sunset 

### ISSUE THREAD

**Issue by Loran425** [csingley/ofxtools#150]
Stumbled across this while working with some financial data, just curious if there is a plan to deprecate the `--ofxhome`  argument in the `ofxget` script following the planned sunsetting of the service later this month?

**Comment by csingley** [comment]
Probably.  It won’t really do much harm when Jay starts sending back 404s though, and I’m pretty busy these days.

If it starts giving you facial tics you could always send in a PR.

**Comment by Loran425** [comment]
Wow that was a fast response,
Thanks for the info, might just look into that.
