### ISSUE TITLE
Trying to get "First Tech Federal Credit Union" OFX download to work

### ISSUE THREAD

**Issue by rkhwaja** [csingley/ofxtools#151]
ofxget returns "Server error occurred.  Received HttpStatusCode of 400" as the response.

The moneydance config at http://moneydance.com/synch/moneydance/fi2004.dict refers to the "discover_http_header_hack" and a list of http headers, which I presume means that the server requires the headers to be sent in a particular order.

Would you accept a patch which allows this as an option?

**Comment by csingley** [comment]
I’m open to it, sure

**Comment by rkhwaja** [comment]
nvm - the header ordering fix doesn't work ;)
