### ISSUE TITLE
Question about multiple user values at same brokerage

### ISSUE THREAD

**Issue by emin63** [csingley/ofxtools#154]
How do I handle the case where I have multiple accounts (with different user names) at the same brokerage?

For example, if I want to manage both my account and my Dad's account at TD Ameritrade, how should I do that? It seems like maybe I can just add another entry in the config file provided I manually fill in fid, org, brokerid, and url like in the example below:

```
[ameritrade_dad]
fid = 5024
org = Ameritrade
brokerid = ameritrade.com
user = dad_username
url = https://ofxs.ameritrade.com/cgi-bin/apps/OFX
```

Does the above look right or should I do something else for the case of multiple user names at the same broker?

**Comment by csingley** [comment]
You got it.  Hey can you please not file bug reports for questions like this?

**Comment by emin63** [comment]
> You got it. Hey can you please not file bug reports for questions like this?

Sorry. I didn't realize you were using the GitHub discussions via https://github.com/csingley/ofxtools/discussions. I will put questions there going forward.

Thanks again.
