### ISSUE TITLE
E*TRADE: "stmt --all" and "acctinfo" broken

### ISSUE THREAD

**Issue by dtbartle** [csingley/ofxtools#168]
Seeing `ofxtools.models.base.OFXSpecError: ofxtools.models doesn't define ACCTID` in `extract_acctinfos`

Best I can tell, E*TRADE has started returning an account with an empty `ACCTID` in response to acctinfo/signon.  The element is there (see following snippet) but is empty:
`
<ACCTINFO>\n<INVACCTINFO>\n<INVACCTFROM>\n<BROKERID>etrade.com\n<ACCTID>\n</INVACCTFROM>\n<USPRODUCTTYPE>NORMAL\n<CHECKING>N\n<SVCSTATUS>ACTIVE\n</INVACCTINFO>\n</ACCTINFO>
`

I'm doing everything programmatically in Python, so I'm happy to handle the missing/empty account (by skipping it), but I'm not able to parse the `request_accounts` response.

**Comment by csingley** [comment]
I mean that's a gross violation of the OFX spec.  Can Quicken even parse this shit?
Library code is correct to raise an error here; mandatory (and functionally critical) data is missing from the input.  Application code needs to handle that error... that's really on you, not me.  Or I guess you could try pushing it upstream & getting the people who are feeding you this crap to clean up their mess.  I am pessimistic about your chances of success with that.
If it's just that one account generating garbage, try closing that account.  I have accounts at Etrade, and have never seen this issue.  If it's a persistent problem, try switching brokers.  The handwriting was on the wall when they shut off their OFX server & cut back their historical data retention to some stupidly small time period.
