### ISSUE TITLE
HTTP Status Code 501 for Chase

### ISSUE THREAD

**Issue by robintanner** [csingley/ofxtools#17]
Anyone getting this when connecting to Chase? 

`C:\Users\robin\Documents\GitHub\ofxtools>python ofxtools\Client.py -u <user> --org chase -C <account> --bankid 111000614 https://ofx.chase.com
Password:
Server error occurred.  Received HttpStatusCode of 501`

**Comment by csingley** [comment]
Hey, I've been trying to help you out, but please don't clutter bug reports with support requests.

Try over on http://www.ofxhome.com/ofxforum/ maybe.

If you log into Chase and click Customer Support > Checking/Savings Account Services > Financial Management Software, I think you'll discover the source of your problems.

**Comment by robintanner** [comment]
You don’t know whether it’s a bug or a support request. 😉 Do you bank with Chase? Have you opened an account to test it?



Thanks

Robin Tanner
Cell: (801) 510-0113



Sent from Mail for Windows 10

**Comment by PierreRochard** [comment]
@robintanner Were you able to get it working with other OFX software? The error message seems to indicate a support request. I bank with Chase and it's working fine.

**Comment by csingley** [comment]
HTTP Status 501 means the problem's on their side.  Chase likes to withhold OFX access unless you have a higher-value relationship or pay a monthly fee or some such.
