### ISSUE TITLE
Error when trying to generate OFX following the doc:  SONRS TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by edsenabr** [csingley/ofxtools#179]
Hi,

I'm trying to produce an OFX file following [this](https://ofxtools.readthedocs.io/en/latest/generating.html) doc, but when I try to create the SONRS object I receive the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
ofx.ipynb Cell 6 line 8
      6 bankmsgsrs = BANKMSGSRSV1(stmttrnrs)
      7 fi = FI(org='Illuminati', fid='666') 
----> 8 sonrs = SONRS(status=status, dtserver=datetime(2015, 1, 2, 17, tzinfo=UTC), language='ENG', fi = fi)
      9 signonmsgs = SIGNONMSGSRSV1(sonrs=sonrs)
     10 ofx = OFX(signonmsgsrsv1=signonmsgs, bankmsgsrsv1=bankmsgsrs)

TypeError: 'module' object is not callable
```

I'm using `ofxtools 0.9.5` on top of `Python 3.10.12`

I tried to go thru the source code of the module, but couldn't find a hint of which changes since version `0.8.22` (which is the one the doc was based on) could be cause of this error.

Any advice ?

**Comment by edsenabr** [comment]
--- BTW, I just tried downgrading my ofxtools to `0.8.22` and got the same error.

**Comment by csingley** [comment]
Is it perhaps the case that in the enclosing scope  `datetime` refers to the module, not the `datetime.datetime` class?

**Comment by edsenabr** [comment]
Yeah, that was the issue. Thanks for the help, @csingley
