### ISSUE TITLE
ACCTID in CCACCTTO in STMTTRN

### ISSUE THREAD

**Issue by rianhunter** [csingley/ofxtools#18]
ofxtools fails to parse this:

    <STMTTRN><CCACCTTO><ACCTID>FOOB</ACCTID></CCACCTTO></STMTTRN>

There are two ways to fix this:
- Make CCACCTTO part of the STMTTRN aggregate, thsi would make `acctid` an attribute of the STMTTRN aggregate. (easy)
- Extend STMTTRN to parse a "sub-aggregate" so that to access `acctid` you'd have to do this: `stmttrn.ccacctto.acctid`.

I'm happy to contribute a PR for this but I'm not sure which strategy is more correct or in the direction of ofxtools.

**Comment by csingley** [comment]
I implemented this in ofxalchemy.Parser.Element by adding a _preflatten() method, but haven't yet ported it back to the main ofxtools.Parser.

The logic won't need to be changed all that much to accomplish that; I just have to drop the SQL lookup to find a foreign key and replace it with code to instantiate a "sub-aggregate". The type converters for BANKACCTTO/CCACCTTO/PAYEE (implementing the aggregate spec) are already there in ofxtools.models.

This needs doing, but it being the peak of audit/tax season, I am unlikely to have time to work on it just now.  You're welcome to work on it in the meantime... the place to look is ofxtools.Response.INVTRANLIST.  What needs to happen is that it should strip BANKACCTTO/CCACCTTO/PAYEE before calling Aggregate.from_etree() on the STMTTRN, separately call Aggregate.from_etree() on the stripped aggregate, and then staple the resulting "sub-aggregate" back onto the instantiated models.STMTTRN.  This should probably happen by adding calls to Element._preflatten() and Element._postflatten() around the current call to Aggregate.from_etree(), then writing the Element._preflatten()/_postflatten() methods based on what's already there in ofxalchemy.Parser.Element (with some tweaks).

**Comment by rianhunter** [comment]
Cool, after looking at the code your recommendation makes sense. I'm working on this right now, could you attach the patch here so I have something to start with? `git diff -a` might make it easy if you haven't yet committed it locally.

**Comment by csingley** [comment]
I haven't actually done any of that, that's just what I plan to do.  The SQL-backed version of this (with the XPath logic) is in the main repo - ofxtools/ofxalchemy/Parser.py - search within for CCACCTTO and you'll see what I did there.

Do me a favor though - if you wind up working on this and make any headway, stick all the DOM mangling in models.Aggregate.from_etree() (not Response.INVTRANLIST as I suggested above).

Something like this:
```

class Aggregate(object):
    @staticmethod
    def from_etree(elem):
        SubClass = globals()[elem.tag]
        foo = SubClass._preflatten(elem)
        instance = SubClass(elem)
        SubClass._postflatten(instance, foo)
        return instance
```
Then just define empty _preflatten()/_postflatten() as dummy methods on Aggregate, and override them on the Aggregate subclasses that need to do work.  That's much better than the stupid if/then testing I've got in the ofxalchemy version.

Just a suggestion - that's how I plan to do it.  Let me know if you need some help before I get around to doing it.

**Comment by rianhunter** [comment]
This all makes sense. PR coming your way soon.
