### ISSUE TITLE
Change acctid from String to NagString

### ISSUE THREAD

**Issue by diraol** [csingley/ofxtools#182]
Hi, my bank (Nubank@Brazil) is feeding my CC statement OFX file with the acctid field being filled up with an UUID. Would it be possible to change the field to use NagString instead of String?

If you are ok with it I can craft the PR.

**Comment by diraol** [comment]
Btw, here is a sample of a CC statement from the before mentioned bank
[br-nu-cc-sample.ofx.txt](https://github.com/csingley/ofxtools/files/14915627/br-nu-cc-sample.ofx.txt)

**Comment by csingley** [comment]
Yeah, sure, why not.

**Comment by diraol** [comment]
Here it is https://github.com/csingley/ofxtools/pull/183
:)
