### ISSUE TITLE
Return value of OFXClient.download() should feed directly into OFXTree.parse()

### ISSUE THREAD

**Issue by rianhunter** [csingley/ofxtools#20]
`OFXClient.download()` now returns a requests `Response` object, which forces me to wrap the `.text` attribute in a `StringIO()` before passing to `OFXTree.parse()`. The way it was before seemed better, where I could pass the file-like object returned from `.download()` directly to `.parse()`. In other words I want to be able to do this:

    tree.parse(client.download(request))

Currently I have to do this:
    
    tree.parse(StringIO(client.download(request).text))

Not sure what the best solution is here:

- Return a `StringIO` from `OFXClient.download()`
- In `OFXClient.download()` set the `requests.post()` `stream` argument to `True` and return the `.raw` attribute from the result.

Depends on whether you think buffering everything at once is preferable or not and/or having access to the requests `Response` object is useful.

**Comment by csingley** [comment]
The thing to understand is that `OFXTree.parse()` hands off to methods (specifically `header.OFXHeader.strip()` and `Parser.TreeBuilder.feed()`) which are just big collections of regexes... in stark contrast with ETree's own stream parser.

I'm pretty sure Python's regex implementation requires that the entire string be buffered or it won't operate correctly.  StringIO is what's needed, and in fact has been utilized successfully for similar purposes in the past, as witnessed by the vestigial StringIO import in Client.py.

Hold the phone, this is coming.

**Comment by csingley** [comment]
Should be fixed in [8715413](https://github.com/csingley/ofxtools/commit/8715413c12cb459cb6197e8802609992ea0a2fcc)
