### ISSUE TITLE
Umlauts are breaking the parser

### ISSUE THREAD

**Issue by chbndrhnns** [csingley/ofxtools#25]
The attached sample file cannot be parsed by `python -c 'from ofxtools import OFXTree; OFXTree().parse("sample.ofx")'`:

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 865: ordinal not in range(128)`

[sample.ofx.txt](https://github.com/csingley/ofxtools/files/1127968/sample.ofx.txt)

The character "ü" is correctly encoded as Windows-1252.

**Comment by csingley** [comment]
OK Meinherr, try with master:
`python -c 'from ofxtools import OFXTree; OFXTree().parse("sample.ofx", codec="cp1252")`

**Comment by chbndrhnns** [comment]
No more error in the master branch.

Can"t we read the codec from the OFX file if it contains those lines?

```
ENCODING:USASCII
CHARSET:1252
```

This would make it implicit.

I came across the error when using `https://github.com/rienafairefr/pynYNAB` where your module is used. For the use case there, automatic detection would be really nice

**Comment by csingley** [comment]
Sure, good idea... it just hasn't come up before.  Give me some time to review the spec (for both OFXv1 & OFXv2) and dig back into header.py, which is some of the oldest code in ofxtools.  It should be pretty easy.

**Comment by csingley** [comment]
Actually won't be that easy to decode the header first without decoding the rest of the payload.  Let me chew on it; it's worthwhile.

**Comment by chbndrhnns** [comment]
What about something like https://stackoverflow.com/a/1767589?

**Comment by csingley** [comment]
That approach has the same chicken & egg issue, but I have an idea how to solve this.

To do this more efficiently, have you perhaps got a CP1252-encoded data file (sanitized of anything you care about) you could send to me?  Bonus points for both OFXv1 and OFXv2.  I do want to get this cleared up; there is no reason for ofxtools to be US-centric when OFX itself has so many pages devoted to i18n.

**Comment by chbndrhnns** [comment]
You can use the one from the bug report.

**Comment by csingley** [comment]
That's what happens when you smoke ketamine while responding to bug reports!  Sorry about that.

I believe I have a satisfactory resolution for the problem.  Try the fix I just checked into master, it's much nicer.

**Comment by chbndrhnns** [comment]
Works fine with me here with my sample docs! Thanks so much!

**Comment by csingley** [comment]
Great, thanks for reporting.
