### ISSUE TITLE
Multiple sequential parsing bug ?

### ISSUE THREAD

**Issue by rienafairefr** [csingley/ofxtools#3]
I don't know if this is a bug: 

    from ofxtools import OFXTree
    
    tree = OFXTree()
    tree.parse('testfile1.ofx')
    response1=tree.convert()
    print(len(response1.statements)) # prints 1
    
    tree2 = OFXTree()
    tree2.parse('testfile2.ofx')
    response2=tree2.convert()
    print(len(response1.statements)) # prints 2

is this expected behavior ?

**Comment by csingley** [comment]
That's a bug.  OFXResponse is appending to the class attribute not the instance attribute.

Thanks, I'll fix it.

**Comment by csingley** [comment]
Fixed in [0cd28aa](https://github.com/csingley/ofxtools/commit/0cd28aa6e8a7d5cb15e739ebb7cd7350724cfc8d)
