### ISSUE TITLE
Python3.3 requirement?

### ISSUE THREAD

**Issue by llpamies** [csingley/ofxtools#30]
I've run the tools with python 3.4 without any apparent issues. Is there any specific reason why the 3.3 requirement is enforced?

https://github.com/csingley/ofxtools/blob/0bcaf80736394c4a2783465f66b27ce7cd0c1d89/setup.py#L58

**Comment by csingley** [comment]
I run it on python 3.6.  What that directive is (supposed to be) saying is that, if you're running python version lower than 3.3, you need to have the mock package installed (mock's in stdlib as of version 3.3).

This is just for testing

**Comment by llpamies** [comment]
Got it. Thanks.
