### ISSUE TITLE
sqlalchemy error: "@declared_attr.cascading is not supported on the __table_args__ attribute"

### ISSUE THREAD

**Issue by skimj** [csingley/ofxtools#34]
```from ofxtools.ofxalchemy import Base, DBSession, OFXParser```

results in many warnings like:

```/usr/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py:98: SAWarning: @declared_attr.cascading is not supported on the __table_args__ attribute on class <class 'ofxtools.ofxalchemy.models.ACCTFROM'>.  This attribute invokes for subclasses in any case.```

I bit of googling got me to [Controlling table inheritance with mixins](http://docs.sqlalchemy.org/en/latest/orm/extensions/declarative/mixins.html#controlling-table-inheritance-with-mixins) from docs.sqlalchemy, specifically:

> Declarative will always invoke `declared_attr` for the special names `__tablename__`, `__mapper_args__` and `__table_args__` function **for each mapped class in the hierarchy, except if overridden in a subclass**.

With near-zero understanding of the code, I think this means that in ofxalchemy/models.py, the `@declared_attr.cascading` decorator is implicit and could be removed from `def __table_args__(cls):` in both `class InheritanceMixin(object):` and `class AcctMixin(object):`

My reservation/naivety is between the sqlalchemy documentation "except if overridden in a subclass" combined with the code comments "Be careful about multiple inheritance.  Subclasses of INV{BUY,SELL} also use \_\_table_args\_\_".

p.s. Thanks for sharing this project. I'm glad I found it, it does exactly what I hoped for.

**Comment by csingley** [comment]
The whole ofxalchemy subpackage was really nothing more than experiment.  I recommend you don't use it, in favor of just using the main OFX parser and declaring your own sqlalchemy models for whichever subset of OFX you're using, and which don't involve such heinous table inheritance.  You'll get a nicer data model that way.

I actually deleted ofxalchemy from the repo, but got a complaint from somebody who'd built something around it.  I put it back in for him, and have kept it working... but cleaning it up to remove warnings generated by my dubious class spaghetti is a bit low on the list of priorities, eh.

Perhaps I should insert some sort of deprecation warning for ofxalchemy.  I mean, it works OK, I just don't think it's a great idea and I'm not working on it any more.

If in fact this approach is not as crazy as I think, and you want to use it... be bold!  Just delete that shit and see what happens.  Don't worry about my warning in the code comments unless you're adding new __table_args__() to a subclass.  I can probably help figure out the new and interesting modes of breakage that may result.

**Comment by skimj** [comment]
OK, good to have your perspective. I originally started down a DIY path and then I sort of shotgunned the ofxalchemy code... and it just worked, so I got more interested in using what you have. Given your comments, I may just try to cherry pick some reusable bits as I really only need a fraction of the data model you've built.

**Comment by skimj** [comment]
I'm really only interested in bank statement/transaction data, so I'm going to take your advice build my own classes/models.

Closing this as "won't fix" but at least it's captured if anyone ever needs it in the future.

**Comment by csingley** [comment]
If you're still interested in using ofxalchemy, I committed the fix that eliminates these warnings.
