### ISSUE TITLE
"OFX Header is malformed" when OFX header not on its own line

### ISSUE THREAD

**Issue by tmerr** [csingley/ofxtools#47]
It looks like the OFX v2 response from my bank (Fidelity Investments) has no newlines whatsoever, which mucks up the logic here: https://github.com/csingley/ofxtools/blob/d8e8a0029e84da63ec1f2dffbb2aa0833e73a3b6/ofxtools/header.py#L52

Is there anything in the spec that guarantees they are on separate lines?

**Comment by csingley** [comment]
Newline separators weren't properly specified in OFXv1.0, but I think this was fixed by OFXv1.5.

Chapter 2 of the OFXv1.6 spec is pretty clear that CRLF is what's wanted.

Fido needs to get with the 21st century yo.  Can you get them to send back OFXv2?  Failing that, have you got a (de-personal-info'ed) response file?

**Comment by tmerr** [comment]
It is OFX v2 if I'm not mistaken-- it looks like this:

    <?xml version="1.0" encoding="UTF-8" standalone="no"?><?OFX OFXHEADER="200" VERSION="203" SECURITY="NONE" OLDFILEUID="NONE" NEWFILEUID="3302fc8d-3522-6a33-352a-736c883884ed"?<OFX>...stuffgoeshere....</OFX>

It parses successfully after the following hack:

    response = io.BytesIO(response.read()
        # fix missing character in ofx header (wtf?)
        .replace(b'?<OFX>', b'?><OFX>')
        # work around github.com/csingley/ofxtools/issues/47
        .replace(b'<', b'\n<'))

**Comment by csingley** [comment]
Oh, OK.

Weeelll... "no newlines" doesn't appear to violate the OFXv2 spec, although this is the first I'm seeing it.  I'll implement more robust parsing in `header.py`.  Not much I can do about unclosed tags though!

Thanks for reporting.

**Comment by tmerr** [comment]
Sg, thanks for the lib

**Comment by csingley** [comment]
Before closing the issue, may I ask you to confirm that  [21c8dde](https://github.com/csingley/ofxtools/commit/21c8dde1bb973210b5510480cc4edc1e0617afe8) actually fixes it for Fido's responses.

**Comment by tmerr** [comment]
That fixes it for fidelity :+1: 
I still need to add the missing character in the header, but can't blame that on this lib
