### ISSUE TITLE
Decimal objects in ElementTree from to_etree()

### ISSUE THREAD

**Issue by stoklund** [csingley/ofxtools#52]
I've been trying to use ofxtools to read-modify-write an OFX file. The write step is failing for me when serializing the `ElementTree`:

```python
root = ofx.to_etree()
tree = ET.ElementTree(root)
print(ET.dump(tree))
```

The `dump()` method is complaining that it can't serialize a `decimal.Decimal` object.

It looks to me like the `Decimal.unconvert()` method in `Types.py` should convert the decimal values to strings:

```python
class Decimal(Element):

    ...

    def unconvert(self, value):
        return str(value)
```

**Comment by csingley** [comment]
Right you are!  Thank you for catching this.  Try the commit linked above (or just pull from master); it should be working.  Let me know if you find anything else.

As it happens I'm in the middle of writing a bunch of tests anyway; you're drawing my attention to coverage I need to add to the `Types` module.

**Comment by stoklund** [comment]
Thanks, it works!
