### ISSUE TITLE
regex in header

### ISSUE THREAD

**Issue by brynan** [csingley/ofxtools#61]
Hello, thanks for all you work on this. I have an ofx that downloads with a SPACE (" ") between the colon ( : ) and the Header value. It seems that is what is throwing a ofxtools.header.OFXHeaderError: OFX header is malformed: 
error. I can over come it by changing the file, but it could help if the regex could accommodate this.
Thanks again.

**Comment by csingley** [comment]
Well that is annoying.  The OFX header is indeed malformed; your bank apparently didn't read section 2.2 of the OFX specification.

Which financial institution is it?

Can you post a full set of the OFX headers from a sample file?

**Comment by brynan** [comment]
The ofx header is...

OFXHEADER: 100
DATA: OFXSGML
VERSION: 102
SECURITY: NONE
ENCODING: USASCII
CHARSET: 1252
COMPRESSION: NONE
OLDFILEUID: NONE
NEWFILEUID: NONE

**Comment by csingley** [comment]
Whose server is generating these malformed headers?

**Comment by brynan** [comment]
Forum Credit Union

**Comment by csingley** [comment]
Thank you.  Apparently Quicken tolerates this, so it's not going to get fixed at the source.

The change you're looking for is harmless and easy to implement & test.  It's not as if strictness in parsing OFXv1 headers is some high-value priority.

The updated regex is in [7d3c344](https://github.com/csingley/ofxtools/commit/7d3c344a15f51f5afc3950f07ac523952199b744); it's also included in release 0.8.10 which is now up on PyPI.

Let me know how it works for you.

**Comment by brynan** [comment]
Thank you for your effort, but now for the noob part of my question. I've tried a few things but how do I go about "updating" to 0.8.10
Whats the right way. :)

**Comment by brynan** [comment]
Well, I think that may have worked.

I used pip to uninstall and then reinstalled and it did install 0.8.10, Is this the "right way"?

And your new regex parsed the malformed headers just fine. No errors.

**Comment by csingley** [comment]
Glad to hear it worked for you.

It's fine to uninstall & reinstall, I do that sometimes.  It's more efficient to say `pip install --upgrade ofxtools`.

Good command line tools are supposed to be self-documenting to some extent.  `pip help` is your friend, e.g. `pip help install`.  If you peer at it, `--upgrade` is listed halfway through the group of install options.

Have fun parsing.
