### ISSUE TITLE
Crash on stmt request

### ISSUE THREAD

**Issue by Zburatorul** [csingley/ofxtools#67]
The following command produces a crash different from #64:
`ofxget stmt citi`
Error log [here.](https://github.com/csingley/ofxtools/files/3582195/error3.log)

while the contents of the config file are:
```
[citi]
version = 220
appver = 2700
creditcard = <valid cc number>
creditline = <valid cc number>
user = <valid user name>
url = https://mobilesoa.citi.com/CitiOFXInterface
pretty = true
```

**Comment by csingley** [comment]
You don't want to use `<ACCTTYPE>CREDITLINE</ACCTTYPE>` for credit cards... that account type is used for (e.g.) a home equity line of credit, and as a child of `<BANKACCOUNTFROM>` it does indeed require you to configure a `<BANKID>` (ABA routing #) as the error message suggests.  Cf. section 11.3.1 of the OFX spec.

However you do not need to configure a routing# for credit card accounts.

**Comment by Zburatorul** [comment]
Indeed the issue went away after dropping the creditline line. Thanks.
