### ISSUE TITLE
Issue getting bank account information and statements from PNC 

### ISSUE THREAD

**Issue by k2parrott** [csingley/ofxtools#68]
Has anyone successfully pulled information from a pnc bank account? I get responses from my requests but they seem to be missing the key information needed for downloading any of my transaction data.
![example return](https://user-images.githubusercontent.com/49169438/65002300-24406b00-d8c1-11e9-87af-54655b9dac5a.png)

**Comment by csingley** [comment]
This is a zombie server.  You're requesting ACCTINFO, but it's responding with an OFX profile instead.  This seems to be what CheckFree does for clients who quit hosting their OFX servers with them.
