### ISSUE TITLE
ofstools with SQL

### ISSUE THREAD

**Issue by dabrown645** [csingley/ofxtools#69]
I am trying to get the sample code in 'Using ofxtools with SQL' in the document working but I am having an issue with this portion.

# Import
client = OFXClient('https://ofxs.ameritrade.com/cgi-bin/apps/OFX',
                   org='Ameritrade Technology Group', fid='AIS',
                   brokerid='ameritrade.com')
stmtrq = InvStmtRq(acctid='999999999')
response = client.request_statements(user='elmerfudd',
                                     password='T0PS3CR3T',
                                     invstmtrqs=[stmtrq])
parser = OFXTree()
parser.parse(response)
ofx = parser.convert()

I am getting  a response of type <class 'http.client.HTTPResponse'> back and it looks like the data from my account but I get "UnsupportedOperation: seek" on parser.parse(response)

---------------------------------------------------------------------------
UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-4-0651381aa92c> in <module>
     66 parser = OFXTree()
     67 print('pre parse')
---> 68 parser.parse(response)
     69 print('pre convert')
     70 ofx = parser.convert()

d:\users\poppie\.virtualenvs\ofx-gztif__g\lib\site-packages\ofxtools\Parser.py in parse(self, source, parser)
     83         logger.info(f"Parsing OFX from {source}")
     84         # Stash the converted OFX header
---> 85         self.header, message = self._read(source)
     86         logger.debug(f"Parsed OFX header: {self.header}")
     87 

d:\users\poppie\.virtualenvs\ofx-gztif__g\lib\site-packages\ofxtools\Parser.py in _read(source)
    116 
    117         try:
--> 118             header, message = parse_header(source)
    119         finally:
    120             if close_source and hasattr(source, "close"):

d:\users\poppie\.virtualenvs\ofx-gztif__g\lib\site-packages\ofxtools\header.py in parse_header(source)
    272         # the spec) and slice the OFX data body from the end of the
    273         # OFX declaration
--> 274         source.seek(0)
    275         decoded_source = source.read().decode(OFXHeaderV2.codec)
    276         header, header_end_index = OFXHeaderV2.parse(decoded_source)

UnsupportedOperation: seek

Is there something else I should do with response before passing it to parser.parse?

**Comment by csingley** [comment]
Crap, I thought I'd fixed that.  `ofxtools.Client.OFXClient.download()` is supposed to return a `BytesIO`, not an `HTTPResponse`.

This is a bug and I'll fix it shortly.  In the meantime, you can just say:
`response = io.BytesIO(response)`
and feed that to `OFXTree.parse()`.

Thank you for reporting this.  Incidentally, if you upgrade to more recent versions of `ofxtools`, the argument signature for `OFXClient.request_statements()` has changed; you no longer need to pack the `InvStmtRq` instances into a sequence, but just pass them as positional arguments.
