### ISSUE TITLE
ofxtools/Client.py:571: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior

### ISSUE THREAD

**Issue by hleofxquotes** [csingley/ofxtools#71]
Test failed

````
$ make test
coverage erase
black --check .
All done! ✨ 🍰 ✨
95 files would be left unchanged.
mypy ofxtools
ofxtools/Client.py:571: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior
Found 1 error in 1 file (checked 52 source files)
make: *** [test] Error 1
````

````
$ python --version
Python 3.7.4
````

**Comment by csingley** [comment]
Huh, I don't get that error on 3.7.4.  Is this ofxtools master, or what version?  What does line 571 of your Client.py say?

**Comment by csingley** [comment]
Now the CI build server is throwing the same error under 3.7.1 ... it didn't used to.
I'll look into it, thanks for reporting.

**Comment by csingley** [comment]
Trivial fix in [
d2ec31d](https://github.com/csingley/ofxtools/commit/d2ec31d0ec4cba66c40833572271a162e0720a57)

**Comment by hleofxquotes** [comment]
Verified fix.
