### ISSUE TITLE
Enhancement request: add flag --writeReqResp <dirName> to write out HTTP headers and OFX request/response

### ISSUE THREAD

**Issue by hleofxquotes** [csingley/ofxtools#76]
Add option to ofxget to write request/response

- HTTP request header
- HTTP response header
- OFX request
- OFX response

to a specified directory. This will help new user to learn what was sent and what was returned from the OFX server.

For example 

````
python ./ofxtools/scripts/ofxget.py  prof amex  --writeReqResp amex
````

Will write to directory 'amex' in current directory the following files
 - amex/request-001-http-request-headers.txt
 - amex/request-001-http-response-headers.txt
 - amex/request-001-ofx-request.txt
 - amex/request-001-ofx-response.txt

in case the 'action' such as (--all) has multiple requests, subsequent requests will get label
 - amex/request-002-http-request-headers.txt
 - amex/request-002-http-response-headers.txt
 - amex/request-002-ofx-request.txt
 - amex/request-002-ofx-response.txt
and so on ...

**Comment by csingley** [comment]
`ofxget` already will dump the RQ/RS, basically:

```
ofxget stmt -n amex > amex/dummy-rq.ofx
ofxget stmt amex > amex/rs.ofx
```

Does this not suffice?

For the headers, I'd think it would be better to log them if desired... but they're not very interesting.

Cf. ofxtools.Client.OFXClient.http_headers(), line 257 et seq.  If you're developing other OFX utilities, I guess what you're looking for is explained in the comment therein... blank User-Agent.
