### ISSUE TITLE
Merrill Edge Bad Request

### ISSUE THREAD

**Issue by rsmulktis** [csingley/ofxtools#77]
Having problems connecting to Merrill. I keep getting 400 Bad Request whether using the ofxget on the command line or the python API directly. Any ideas/suggestions?

**Comment by csingley** [comment]
Sorry, never have con  Ifnected to Merrill.

Try varying the URL slightly and see if it gives you a different error msg.  If the same error msg, that probably means the service doesn't live at that URL anymore.  If different error msg, it might be you're talking to the OFX server but your request is failing... some of the OFX servers throw HTTP errors if you don't pass some preliminary connection hurdles.
