### ISSUE TITLE
Discover support

### ISSUE THREAD

**Issue by RadicalAcronym** [csingley/ofxtools#79]
I found a printout of the discover log from a quicken pull down. Hoping someone will help get this to work. Here it is below with MASKED and stuff after that being the only things that aren't exact

<OFX>
<SIGNONMSGSRQV1>
<SONRQ>
<DTCLIENT>202004221100220.111[-4:EDT]
<USERID>MASKEDUSERID
<USERPASS>X<GENUSERKEY>N
<LANGUAGE>ENG
<FI>
<ORG>Discover Financial Services
<FID>7101
</FI>
<APPID>QWIN 
<APPVER>2500
</SONRQ>
</SIGNONMSGSRQV1>
<CREDITCARDMSGSRQV1>
<CCSTMTTRNRQ>
<TRNUID>MASKEDUUID4
<CCSTMTRQ>
<CCACCTFROM>
<ACCTID>MASKEDACCNTINFORMATION
</CCACCTFROM>
<INCTRAN>
<DTSTART>20200301
<INCLUDE>Y
</INCTRAN>
</CCSTMTRQ>
</CCSTMTTRNRQ>
</CREDITCARDMSGSRQV1>
</OFX>

**Comment by aclindsa** [comment]
I do not personally have any Discover accounts, but my understanding is that Discover requires the HTTP headers to be precisely the way they want them to be:

https://github.com/aclindsa/ofxgo/blob/master/discovercard_client.go#L52

**Comment by csingley** [comment]
@aclindsa good stuff!  Strength to your arm.  Do not be influenced by GnuCash's pernicious rejection of GAAP as it relates to accounting for unrealized gains in financial securities.

**Comment by gtTracy** [comment]
Any way to get this working with ofxget? I have tried using the OFX Home code, and tried manually setting the URL, FID, and ORG in ofxget.cfg - neither seems to work. Setting ofxget.cfg containing the following entries:

```
[disc]
url = https://ofx.discovercard.com:443
fid = 9625
org = Discover Card Account Center

```
then issuing `ofxget prof disc`, I get back the following:

```
Traceback (most recent call last):
  File "/home/tracy/.local/bin/ofxget", line 8, in <module>
    sys.exit(main())
  File "/home/tracy/.local/lib/python3.8/site-packages/ofxtools/scripts/ofxget.py", line 1590, in main
    REQUEST_HANDLERS[args["request"]](args)
  File "/home/tracy/.local/lib/python3.8/site-packages/ofxtools/scripts/ofxget.py", line 572, in request_profile
    with client.request_profile(
  File "/home/tracy/.local/lib/python3.8/site-packages/ofxtools/Client.py", line 492, in request_profile
    response = self._request_profile(
  File "/home/tracy/.local/lib/python3.8/site-packages/ofxtools/Client.py", line 567, in _request_profile
    return self.download(
  File "/home/tracy/.local/lib/python3.8/site-packages/ofxtools/Client.py", line 863, in download
    response = url_opener(req, **kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

```

I'd be happy to try any configuration changes or even updated code, if that's what's needed (I would look at the code and see if I could figure it out, but I don't know python, and my coding skills are over a decade out of date)...

**Comment by aclindsa** [comment]
@csingley can correct me, but I don't believe there is currently an option in `ofxget` to allow forcing the HTTP headers to be in the exact format/order that Discover requires. As per a [discussion from 2018](https://github.com/aclindsa/ofxgo/pull/6), it does appear that someone without a Discover login ought to be able to reproduce this behavior if someone is interested in attempting a fix.

**Comment by gtTracy** [comment]
Thanks for that. So - at least for the moment - it would seem that Discover is off the table. I'll keep an eye out here in case that changes (and if I ever find the time, maybe I'll poke in the code and see if I can figure anything out - with no background or working knowledge of Python, I find that unlikely, but...)
