### ISSUE TITLE
Option to *not* use keyring

### ISSUE THREAD

**Issue by rvernica** [csingley/ofxtools#85]
I have `python-keyring` installed (required by other packages), but I do **not** want `ofxget` to use it. It is not configured properly and `ofxget` tries to use it and errors out:
```
> ofxget stmt ...
Traceback (most recent call last):
  File "/.local/bin/ofxget", line 8, in <module>
    sys.exit(main())
  File "/.local/lib/python3.8/site-packages/ofxtools/scripts/ofxget.py", line 1499, in main
    REQUEST_HANDLERS[args["request"]](args)
  File "/.local/lib/python3.8/site-packages/ofxtools/scripts/ofxget.py", line 609, in request_stmt
    password = get_passwd(args)
  File "/.local/lib/python3.8/site-packages/ofxtools/scripts/ofxget.py", line 1445, in get_passwd
    password = keyring.get_password("ofxtools", server) or ""
  File "/.local/lib/python3.8/site-packages/keyring/core.py", line 56, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/.local/lib/python3.8/site-packages/keyring/backends/fail.py", line 25, in get_password
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
```

As a workaround, it seems that I can use the `--savepass` parameter. An error is displayed at the end of the process and the download succeeds.

Version info:
```
> python
Python 3.8.3 (default, May 29 2020, 00:00:00) 
[GCC 10.1.1 20200507 (Red Hat 10.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ofxtools
>>> ofxtools.__version__
'0.8.20'
```

**Comment by csingley** [comment]
Well that's reasonable.  I'm quite happy using the keyring, but certainly nobody should be forced to use it.

This whole feature is pretty new/experimental in the first place, as you can see from the poor error handling.  Let me work on it a bit and I'll push something a little less hamhanded for you.

**Comment by csingley** [comment]
OK, give the `--nokeypass` option in [7674b0d](https://github.com/csingley/ofxtools/commit/7674b0d77225330fcef3d73a624a77b237d29d3b) a shot.

BTW you don't have `ofxtools` installed in a virtualenv do you?  I do (for dev & test purposes), and I noticed it was throwing me the same error (i.e `keyring.errors.NoKeyringError`) when `python-keyring` was installed in the system python but not the venv Python.  These cleared up when I installed `python-keyring` in the venv.

**Comment by rvernica** [comment]
No, no virtual environment.

I removed the package and installed the latest from git. It worked without requiring any extra parameter. I also tried with `--nokeyring` (I think you have a typo in your comment above) and that worked as well. Thanks!

**Comment by csingley** [comment]
Yep, you're seeing intended behavior - the result of improved error handling.  If the user's keyring can't be accessed, we should fall back to manual import.  `--nokeyring` only applies to suppress a keyring otherwise accessible to `ofxget`.

Cool cool cool.  Thanks for reporting.
