### ISSUE TITLE
"Malformed Header" for Wells Fargo qfx files

### ISSUE THREAD

**Issue by ar090** [csingley/ofxtools#89]
Thank you for the great library! I've been using it in production now for a few weeks and noticed an issue that seems consistent with all Wells Fargo outputs.

Wells Fargo seems to smash the whole file into one line including the header. Is this valid format or something you would consider supporting? This is something I will have to support either way, so any direction on where I can extend the desired behavior if not would be greatly appreciated.

Attached is an anonymized sample report example:
```
OFXHEADER:100DATA:OFXSGMLVERSION:102SECURITY:NONEENCODING:USASCIICHARSET:1252COMPRESSION:NONEOLDFILEUID:NONENEWFILEUID:NONE<OFX><SIGNONMSGSRSV1><SONRS><STATUS><CODE>0<SEVERITY>INFO<MESSAGE>SUCCESS</STATUS><DTSERVER>20200818065106.132[-7:PDT]<LANGUAGE>ENG<FI><ORG>WF<FID>3000</FI><SESSCOOKIE>a6a12496-682d-42b2-aafa-ed973c406a17-08182020075105922<INTU.BID>3000<INTU.USERID>jdoe</SONRS></SIGNONMSGSRSV1><BANKMSGSRSV1><STMTTRNRS><TRNUID>0<STATUS><CODE>0<SEVERITY>INFO<MESSAGE>SUCCESS</STATUS><STMTRS><CURDEF>USD<BANKACCTFROM><BANKID>121042882<ACCTID>5555555555<ACCTTYPE>CHECKING</BANKACCTFROM><BANKTRANLIST><DTSTART>20200101120000.000[-8:PST]<DTEND>20200810110000.000[-7:PDT]<STMTTRN><TRNTYPE>CREDIT<DTPOSTED>20200403110000.000[-7:PDT]<TRNAMT>507500.00<FITID>202004031<NAME>TD AMERITRADE CLEARING<MEMO>WT SEQ555555 /ORG=JOHN DOE SRF# EC55555555555 TRN#55555555555 RFB# 55555555555</STMTTRN></BANKTRANLIST><LEDGERBAL><BALAMT>56498.04<DTASOF>20200817110000.000[-7:PDT]</LEDGERBAL><AVAILBAL><BALAMT>56498.04<DTASOF>20200817110000.000[-7:PDT]</AVAILBAL></STMTRS></STMTTRNRS></BANKMSGSRSV1></OFX>
```

**Comment by csingley** [comment]
Well, huh.  Scrutiny of the 1.0.2 spec (specifically section 2.2) seems to indicate no explicit requirement that the fields of OFX header must be separated by line breaks.. it's STUPID, mind you, and contradicted by every example ever given by the writers of the spec, but apparently not actually ILLEGAL.  The OFX header isn't SGML, so isn't covered by the DTD; the Word doc is all we've got.  In this respect, `ofxtools` header parsing is stricter than the spec... and more to the point, we're stricter than Quicken, which apparently doesn't barf on this construction (else WFC would certainly fix it).  This seems unnecessarily harsh.

BTW WFC is in fact explicitly violating the OFX 1.0.2 spec by not separating the OFX header from the SGML tag soup via line breaks, but I think I gave up on that many years ago; IIRC this shouldn't break `ofxtools` parsing in & of itself.

No, what we're talking about here is `ofxtools.header.OFXHeaderV1.regex` (currently line 105).  It should suffice to edit each line of the regex to change the final 3 characters from `/s+` to `/s*`, no?

**Comment by csingley** [comment]
Having changed the regex thus:

```
In [1]: import ofxtools                                                                                                                                                 
In [2]: from io import BytesIO                                                                                                                                          
In [3]: response = BytesIO(b"OFXHEADER:100DATA:OFXSGMLVERSION:102SECURITY:NONEENCODING:USASCIICHARSET:1252COMPRESSION:NONEOLDFILEUID:NONENEWFILEUID:NONE<OFX><SIGNONMSGS
   ...: RSV1><SONRS><STATUS><CODE>0<SEVERITY>INFO<MESSAGE>SUCCESS</STATUS><DTSERVER>20200818065106.132[-7:PDT]<LANGUAGE>ENG<FI><ORG>WF<FID>3000</FI><SESSCOOKIE>a6a12496
   ...: -682d-42b2-aafa-ed973c406a17-08182020075105922<INTU.BID>3000<INTU.USERID>jdoe</SONRS></SIGNONMSGSRSV1><BANKMSGSRSV1><STMTTRNRS><TRNUID>0<STATUS><CODE>0<SEVERITY
   ...: >INFO<MESSAGE>SUCCESS</STATUS><STMTRS><CURDEF>USD<BANKACCTFROM><BANKID>121042882<ACCTID>5555555555<ACCTTYPE>CHECKING</BANKACCTFROM><BANKTRANLIST><DTSTART>202001
   ...: 01120000.000[-8:PST]<DTEND>20200810110000.000[-7:PDT]<STMTTRN><TRNTYPE>CREDIT<DTPOSTED>20200403110000.000[-7:PDT]<TRNAMT>507500.00<FITID>202004031<NAME>TD AMERI
   ...: TRADE CLEARING<MEMO>WT SEQ555555 /ORG=JOHN DOE SRF# EC55555555555 TRN#55555555555 RFB# 55555555555</STMTTRN></BANKTRANLIST><LEDGERBAL><BALAMT>56498.04<DTASOF>20
   ...: 200817110000.000[-7:PDT]</LEDGERBAL><AVAILBAL><BALAMT>56498.04<DTASOF>20200817110000.000[-7:PDT]</AVAILBAL></STMTRS></STMTTRNRS></BANKMSGSRSV1></OFX>")         
In [4]: parser = ofxtools.Parser.OFXTree()                                                                                                                              
In [5]: root = parser.parse(response)                                                                                                                                   
In [6]: root[:]                                                                                                                                                         
Out[6]: 
[<Element 'SIGNONMSGSRSV1' at 0x7f7b8e529bd0>,
 <Element 'BANKMSGSRSV1' at 0x7f7b8e52b0e0>]
```

**Comment by ar090** [comment]
Awesome! Thanks for the background and cant thank you enough for the quick response. That looks good to me but I'm drastically uneducated in terms of whether or not this would impact existing cases you are covering for. Is the regex change something you would be willing to merge/publish? Otherwise we can override on our end to `/s*`. Would definitely prefer the former to keep our integration clean but totally your call.

**Comment by csingley** [comment]
Nah I'll push a change, for sure, there's just a little bit of a process (writing unit tests etc.)

While I'm doing that... if you have a bunch of live data to use as test cases, do me a favor and run the patched parser over it (both WFC and otherwise) to see if we can catch any related bugs while they're hot.

**Comment by ar090** [comment]
For sure happy to help. So here is the changes I made from your suggestion ->
![image](https://user-images.githubusercontent.com/17073553/90577078-dfd2e480-e18d-11ea-95d3-206340085307.png)

I tested 11 files from different banks, chase, wf, svb etc. While your fix allows the files to parse, i'm unable to dig into the actual transactions. Specifically -> 
![image](https://user-images.githubusercontent.com/17073553/90577245-5b349600-e18e-11ea-9c97-2ccadb432498.png)

Now my ways for doing so may be off, however it works fine for the non wells files ->
```
from ofxtools.header import OFXHeaderError
from ofxtools.Parser import OFXTree
import os

DIR = 'ofx'

header_errors = 0
files = os.listdir('ofx')
print(f'Testing {len(files)} files')
for file in os.listdir('ofx'):
	with open(os.path.join(DIR, file), 'rb') as f:
		parser = OFXTree()
		parser.parse(f)
		ofx = parser.convert()
		for statement in ofx.statements:
			for txn in statement.transactions:
				assert txn.trnamt
				assert txn.fitid

print('Num header errors:', header_errors)
```

**Comment by csingley** [comment]
That's odd.  Continuing my interactive session in the comment above, using your anonymized sample (you should be able to duplicate these results verbatim in your own interpreter):
```
In [7]: ofx = parser.convert()                                                                                                                                          
In [8]: ofx                                                                                                                                                             
Out[8]: <OFX fid='3000' org='WF' len(statements)=1 len(securities)=0>
In [9]: ofx.statements[0]                                                                                                                                               
Out[9]: <STMTRS(curdef='USD', bankacctfrom=<BANKACCTFROM(bankid='121042882', acctid='5555555555', accttype='CHECKING')>, banktranlist=<BANKTRANLIST dtstart='2020-01-01 20:00:00+00:00' dtend='2020-08-10 18:00:00+00:00' len=1>, ledgerbal=<LEDGERBAL(balamt=Decimal('56498.04'), dtasof=datetime.datetime(2020, 8, 17, 18, 0, tzinfo=<UTC>))>, availbal=<AVAILBAL(balamt=Decimal('56498.04'), dtasof=datetime.datetime(2020, 8, 17, 18, 0, tzinfo=<UTC>))>)>
```

The WFC files may have more problems than just the OFX header formatting...

**Comment by csingley** [comment]
I also ran the patched parser over a decade or so of OFX data from a few different accounts, no problem.  Something about your WFC files is breaking `ofxtools.Parser.parse()`.

**Comment by ar090** [comment]
Ok so good news is even the code from your interactive session isn't reproducible for me which tells me I've probably butchered the patch. Bad news is I'm not sure how being that my only code change is in the screenshot above. Exact snippet and the result:
```
import ofxtools    
from io import BytesIO
response = BytesIO(b"OFXHEADER:100DATA:OFXSGMLVERSION:102SECURITY:NONEENCODING:USASCIICHARSET:1252COMPRESSION:NONEOLDFILEUID:NONENEWFILEUID:NONE<OFX><SIGNONMSGSRSV1><SONRS><STATUS><CODE>0<SEVERITY>INFO<MESSAGE>SUCCESS</STATUS><DTSERVER>20200818065106.132[-7:PDT]<LANGUAGE>ENG<FI><ORG>WF<FID>3000</FI><SESSCOOKIE>a6a12496-682d-42b2-aafa-ed973c406a17-08182020075105922<INTU.BID>3000<INTU.USERID>jdoe</SONRS></SIGNONMSGSRSV1><BANKMSGSRSV1><STMTTRNRS><TRNUID>0<STATUS><CODE>0<SEVERITY>INFO<MESSAGE>SUCCESS</STATUS><STMTRS><CURDEF>USD<BANKACCTFROM><BANKID>121042882<ACCTID>5555555555<ACCTTYPE>CHECKING</BANKACCTFROM><BANKTRANLIST><DTSTART>20200101120000.000[-8:PST]<DTEND>20200810110000.000[-7:PDT]<STMTTRN><TRNTYPE>CREDIT<DTPOSTED>20200403110000.000[-7:PDT]<TRNAMT>507500.00<FITID>202004031<NAME>TD AMERITRADE CLEARING<MEMO>WT SEQ555555 /ORG=JOHN DOE SRF# EC55555555555 TRN#55555555555 RFB# 55555555555</STMTTRN></BANKTRANLIST><LEDGERBAL><BALAMT>56498.04<DTASOF>20200817110000.000[-7:PDT]</LEDGERBAL><AVAILBAL><BALAMT>56498.04<DTASOF>20200817110000.000[-7:PDT]</AVAILBAL></STMTRS></STMTTRNRS></BANKMSGSRSV1></OFX>")
parser = ofxtools.Parser.OFXTree()
root = parser.parse(response)
root[:]
```
![image](https://user-images.githubusercontent.com/17073553/90583255-b8841380-e19d-11ea-9264-0138eb343f9c.png)

After debugging for a bit I believe the reason for this is from `parse_header`. I get thrown into this else block and ultimately `message` is `''` -> 
![image](https://user-images.githubusercontent.com/17073553/90584748-4f060400-e1a1-11ea-9a2b-f4a493a2bc11.png)

This has to be a pad parse result from my regex change if you could take a closer look. I tried a fresh environment with version `0.8.21` just to sanity check. Same results. Let me know what you think and apologies in advance if I am missing something silly.

**Comment by csingley** [comment]
Well let's make sure we're on the same code.  I just pushed the regex change as [2a50996](https://github.com/csingley/ofxtools/commit/2a50996e2f6b4b1c0f14b94675f771079a9258dd); see what those results are and we can go from there.

**Comment by ar090** [comment]
Boom that commit looks great! Results from my original script ->
![image](https://user-images.githubusercontent.com/17073553/90637954-a6848e00-e1fa-11ea-9a89-221974375c09.png)

**Comment by ar090** [comment]
Any chance you could publish a new version for this commit?

**Comment by csingley** [comment]
[Your wish is my command, sahib.](https://pypi.org/project/ofxtools/0.8.22/)
